#!/usr/bin/env python3

import argparse
import os
import pathlib
import shutil
import subprocess


current_env = os.environ.copy()


def run(cmd, check=True, shell=False, env=None, **kwargs):
    new_env = current_env.update(env)
    if shell:
        return subprocess.run(cmd, check=check, shell=True, env=new_env, **kwargs)
    else:
        return subprocess.run(cmd.split(), check=check, shell=False, env=new_env, **kwargs)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--lma', action='store_true', help='clone lma repos and create lma model')
    parser.add_argument('--lxd', action='store_true', help='Set up a lxd cloud (Not repeatable)')
    parser.add_argument('--k8s', action='store_true', help='Set up a k8s cloud (Not repeatable)')
    parser.add_argument('--reinstall', action='store_true', help='Completely uninstall juju and microk8s first')
    parser.add_argument('--juju-channel', action='store', default='latest/stable', help='The snap channel to install juju from')
    parser.add_argument('--agent-version', action='store', help='Version of the juju agent to ask for during bootstrap')
    return parser.parse_args()


def setup_lxd():
    run('sudo snap install lxd')
    run('sudo lxd init --auto')
    run('lxc network set lxdbr0 ipv6.address none')
    run('juju bootstrap localhost')


def setup_k8s(agent_version):
    run('sudo snap install microk8s --classic')
    run('sudo snap alias microk8s.kubectl kubectl')
    run('sudo microk8s status --wait-ready')
    run('sudo microk8s enable storage dns dashboard ingress')
    run('sleep 180')
    run('sudo microk8s config | juju add-k8s mk8s --client', shell=True)
    agent_arg = f'--agent-version {agent_version}' if agent_version else ''
    run(f'juju bootstrap {agent_arg} mk8s')
    run('sudo usermod -a -G microk8s $USER', shell=True)



def main():
    args = parse_args()

    if args.reinstall:
        run('sudo snap remove juju --purge')
        run('sudo snap remove microk8s --purge')
        jujudir = os.path.expanduser('~/.local/share/juju')
        run(f'rm -rf {jujudir}')

    apt_env = {'DEBIAN_FRONTEND': 'noninteractive'}
    run('sudo apt-get update')
    run('sudo apt-get -yq dist-upgrade', env=apt_env)
    run('sudo apt-get -yq install make virtualenv', env=apt_env)
    run(f'sudo snap install juju --classic --channel {args.juju_channel}')
    run('sudo snap install juju-wait --classic')
    run('sudo snap install charmcraft --classic')
    pathlib.Path('~/.aliases.d').expanduser().mkdir(exist_ok=True)
    shutil.copy('juju.aliases', pathlib.Path('~/.aliases.d').expanduser())

    if args.lxd:
        setup_lxd()
    if args.k8s:
        setup_k8s(args.agent_version)

    if args.lma:
        curdir = os.getcwd()
        try:
            os.chdir(os.environ['HOME'])
            if not os.path.exists('grafana'):
                run('git clone git@github.com:canonical/grafana-operator.git grafana')
            if not os.path.exists('prometheus'):
                run('git clone git@github.com:canonical/prometheus-operator.git prometheus')
            if not os.path.exists('alertmanager'):
                run('git clone git@github.com:canonical/alertmanager-operator.git alertmanager')
            if not os.path.exists('cassandra'):
                run('git clone git@github.com:canonical/cassandra-operator.git cassandra')
            if not os.path.exists('agent'):
                run('git clone git@github.com:canonical/grafana-agent-operator.git agent')
            if not os.path.exists('loki'):
                run('git clone git@github.com:canonical/loki-operator.git loki')
            for line in run('juju list-models', capture_output=True, encoding='utf-8').stdout.splitlines():
                if line.startswith('lma'):
                    break
            else:
                run('juju add-model lma')
                run('juju model-config update-status-hook-interval=30s')
                run('kubectl config set-context --current --namespace=lma')
        finally:
            os.chdir(curdir)


if __name__ == '__main__':
    main()
